#!/bin/bash
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #1 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Hideous_Destructor.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #2 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/DoomRL_Arsenal.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #3 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Guncaster.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #4 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Colourful_Hell.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #4 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Project_MSX.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #4 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Russian_Overkill.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #7 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/GMOTA.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #8 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/High_Noon_Drifter.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #8 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Netronian_Chaos.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #10 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Hearts_of_Demons_-_BARON.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #11 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Psychic.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #12 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Samsara.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #13 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Reelism.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #14 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Doom_RPG.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #14 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Final_Doomer.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #14 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/LegenDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #14 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Trailblazer.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #18 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Adventures_of_Square.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #19 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Zen_Dynamics.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #20 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/D4D.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #20 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/La_Tailor_Girl.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #22 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Pirate_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #22 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Urban_Brawl:_Action_Doom_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #24 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Demonsteele.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #24 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Touhou_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #26 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Ashes_2063_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #26 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/JohnnyDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #26 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/MetaDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #26 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/ouch_m_2:_abort_m.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #26 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/PlayStation_Doom_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #26 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Ghoul_s_Forest_3.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #26 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Winter_s_Fury.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #33 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Blade_of_Agony.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #33 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Daytime_Drama.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #33 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Doom_Incarnate.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #33 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Quake_Champions:_Doom_Edition.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Faspons.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Legacy_of_Suffering.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Lithium.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Project_Einherjar.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/RTC-3057_Hub_1.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Terrorists!.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Soldier_Z.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Ultimate_Torment_and_Torture.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/10x.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/AEons_Of_Death.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Death_Foretold.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Doom_64:_Retribution.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Hunter’s_Moon.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Kriegsland:_Blutorden.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/SpriteShadow.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Zero_Tolerance.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Beautiful_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Burl_Tumd.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Jimmy’s_Jukebox.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Juvenile_Power_Fantasy.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Redux_E2M4.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Shut_up_and_Bleed.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Strange_Aeons.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Stronghold:_On_the_Edge_of_Chaos.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Sun_Damage_Omen.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Super_Sonic_DooM.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Ultimate_Simpsons_Doom_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Void.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #53 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Waterlab_GZD.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Action_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Aetherius.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Aracnocide.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/BlackWarrior.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Brutal_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Castlevania_-_Simon_s_Destiny.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Crossfire.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Dead_Marine.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Demon_CounterStrike.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Doom_Delta.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Droplets:_Simulated_Blood.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Eriguns_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Error:_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Ghoul_School_3D.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/HeXeReTiC_Fantasy.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Hocusdoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Insanity_s_Requiem.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Queen_s_Crusade.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Shades_of_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Space_Pirate.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Unloved.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Weapons_of_Saturn.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Wrath_of_Cronos_RPG.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #66 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/WW-Cola3.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/007:_Licence_to_Spell_DooM.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Accessories_to_Murder.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Alandoguns.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Alfonzone.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/All_Clear_Message.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Argent.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Banhammer.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Brutalkick.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Chex_Quest_3.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Chosen.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Complex_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Complex_Doom:_LCA.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Consolation_Prize:_The_PSX_Doom_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/CustomDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/DamNums.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Dark_7__with_Mission_Pack_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Dark_Encounters.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Demon_Eclipse.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Demonsteele:_NowThatsWhatICallMIDI.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Doom_2_Minor_Sprite_Fixing_Project.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Doom_64__weapons_only_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Doom:_The_Golden_Souls.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Eriguns_1.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Factotum.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Fading_Corpses_Universal.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/FamiliarDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Final_NeoDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Footsteps.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/GZSHud.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Heretic_Widescreened_HUD.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/HeXercise.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Highway_to_Hell.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Hordes_of_Chaos.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/HXRTC_Project.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/MassMouth_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Megabounce.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Metroid:_Dreadnought.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Monster_Scouter.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Nash_s_Gore_Mod.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Nazis!.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/NC_HUD.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/njsplash.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Paranoid_and_Paranoiac.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Perkristan_s_HD_Sounds.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Pokémon_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/QUAKE:_Descent_into_Heresy.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Reikall_s_Voxels.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Runaway_Train.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Sbrightmaps.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/scalliano_s_667_Shuffle.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Serpent_Resurrection.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Simple_Mirrored_Monsters.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Skulldash.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Smooth_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Smooth_fluids.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Sound_Caulking.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/StatsKeeper.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/TGRDM3__Morgenstern_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Inquisitor_III.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/The_Trooper.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/Tilt++.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #90 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' pngs/WARDUST_heretic_Sprites.png
optipng pngs/*
