#!/bin/bash
rm pngs/*

convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #1 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hideous_Destructor.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #2 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Guncaster.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #3 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Project_Brutality.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #4 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/DoomRL_Arsenal.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #5 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Quake_Champions:_Doom_Edition__QCDE_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #5 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Trailblazer.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #7 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/High_Noon_Drifter.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #7 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Russian_Overkill.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #9 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Death_Foretold__D4T_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #10 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Final_Doomer.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #11 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Project_MSX.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #12 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Netronian_Chaos.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #13 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Winter_s_Fury.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #14 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Colourful_Hell.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #14 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/GMOTA.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #16 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Samsara.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #16 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Adventures_of_Square.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #18 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Ashes_2063_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #18 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hearts_of_Demons_-_BARON.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #20 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Demonsteele.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #20 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Touhou_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #22 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Blade_of_Agony.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #23 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Urban_Brawl:_Action_Doom_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #24 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Brutal_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #24 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/DOOM_For_DooM__D4D_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #24 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_Incarnate.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #24 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Enhanced_Vanilla_Project__EVP_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #28 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/La_Tailor_Girl.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #28 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Psychic.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #30 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Beautiful_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #31 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_RPG.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #31 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hedon.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #31 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Reelism.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #34 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Nash_s_Gore_Mod.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #35 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom:_The_Golden_Souls_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #35 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Lithium.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/LegenDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #37 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Smooth_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #39 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_64:_Retribution.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #39 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hexen:_Walpurgis.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #39 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hunter’s_Moon.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #39 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Kriegsland:_Blutorden.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #39 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/MetaDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #39 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Slayer_s_Rampage.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Pirate_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #45 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Ultimate_DoomVisor.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #47 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom:_The_Golden_Souls.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #47 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Wrath_of_Cronos_RPG.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #47 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Zen_Dynamics.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #50 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Legacy_of_Suffering.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #50 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/m8f’s_toolbox.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #50 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/ouch_m_2:_abort_m.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #50 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Shadow_Of_The_Wool_Ball.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #50 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Inquisitor_III.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #50 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Ultimate_Torment_and_Torture.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #56 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hocusdoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #56 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/PlayStation_Doom_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #58 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/HexArcana.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #58 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Rise_Of_The_Wool_Ball.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #58 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/WW-Cola3.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Aracnocide.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Daytime_Drama.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_Delta.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/DTS-T.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Faspons.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Project_Einherjar.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Reikall_s_Voxels.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Weapons_of_Saturn.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Zagemod.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #61 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Zero_Tolerance.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/AEons_Of_Death.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Brutal_Doom_64.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Happy_Time_Circus_][.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/JohnnyDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Nazis!.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/RTC-3057_Hub_1.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/S.U.P.E.R_Natural.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Soundless_Mound.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Stronghold:_On_the_Edge_of_Chaos.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Terrorists!.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Soldier_Z.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Threshold_Of_Pain.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #71 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Unloved.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/10x.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Action_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Argent.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/BGPA_Missions_Liberation.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Bratwurst.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Bullet-Eye.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Burl_Tumd.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Demon_Eclipse.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Droplets:_Simulated_Blood.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hell-Forged.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/HXRTC_Project.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Juvenile_Power_Fantasy.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/NC_HUD.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Perkristan_s_HD_Sounds.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Reelism_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Serpent_Resurrection.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Shades_of_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Shut_up_and_Bleed.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/SpriteShadow.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Total_Chaos.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Waterlab_GZD.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #84 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Who_Dun_It.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Alandoguns.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Aliens:_Eradication.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Call_of_Dooty.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Castlevania_-_Simon_s_Destiny.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Cold_as_Hell.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Combined_Arms.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Compendium.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Complex_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/DamNums.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Dark_Encounters.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Diaz:_Last_Hours_of_Purity.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Factotum.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Full_GZDoom_Skybox_Set.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Happy_Time_Circus.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Insanity_s_Requiem.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Jimmy’s_Jukebox.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/PlayStation_Doom_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Redux_E2M4.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/scalliano_s_667_Shuffle.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Strange_Aeons.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Super_Sonic_DooM.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Ghoul_s_Forest_3.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Treasure_Tech.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Void.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/WolfenDOOM:_Operation:_Arctic_Wolf.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #106 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/ZBlood+.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Aetherius.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/All_Clear_Message.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Ascension.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/BlackWarrior.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Consolation_Prize:_The_PSX_Doom_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Crossfire.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Cyberrunner.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Dead_Marine.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/dead.air.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Demon_CounterStrike.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Eriguns_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Error:_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Final_NeoDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Footsteps.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/FragTrak.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Gene-Tech:_Before_the_Storm.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Gothic_Skins_for_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Heretical_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/HeXeReTiC_Fantasy.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Lambda.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/MassMouth_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Midgard_Outlaw.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Nightshift.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Paranoid_and_Paranoiac.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/QUAKE:_Descent_into_Heresy.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Queen_s_Crusade.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/SBrightmaps.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Skulldash.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Sneaky_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Sound_Caulking.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Spooktober_Community_Mapping_Project.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Temple_of_the_Lizard_Men_4.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Space_Pirate.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Wayfarer_s_Tome_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Tilt++.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Town_Infection:_The_Flooding.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/TurboCharged_ARCADE!.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Ugly_as_Sin.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Ultra_Crispy.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #132 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/WolfenDOOM:_Astrostein.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/007:_Licence_to_Spell_DooM.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/20_Monsters_Challenge.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Abandoned_Misery.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Accessories_to_Murder.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Alfonzone.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Aliens:_Colonial_Marines_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/AvP_2.0.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Banhammer.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Beyond_Reality.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Bitter_Heretic.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Brutal_Doom:_Tomtefars_Extension.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Brutalkick.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/CBLOOD_Ultimate_Edition.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Champions.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Cheogsh.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Cheogsh_2.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Chosen.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Complex_Doom:_LCA.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Counter-Strike_Doom:_Martian_Offensive.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Custom_Crosshair_Pack_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Dark_7__with_Mission_Pack_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/DarkDoomZ.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Darkmoon.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Dawn_of_Reality.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Demonsteele:_NowThatsWhatICallMIDI.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Don’t_play_with_HELL_–_Black_Edition.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_2_Minor_Sprite_Fixing_Project.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/DOOM_4_VANILLA.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_64__weapons_only_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_Ambient_Pack.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_Loot_Box_Mod.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Doom_Raider:Crypt_of_the_Vile.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/DoomKrakken_s_Monster_Randomizer.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Embers_Of_Armageddon.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Eriguns_1.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Eternal_DOOM_IV:_Return_from_Oblivion.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/FamiliarDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Foreverhood.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Ghoul_School_3D.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/GZSHud.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Harder_Event.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Haze.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Heretic_Widescreened_HUD.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hexen:_Scourge_of_Viscerus.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/HeXercise.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Highway_Acceleroid_Booster.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/HitMarkers.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Hordes_of_Chaos.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/JP_s_HUD.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Karnak.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Keymaster.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Lasting_Light.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Lilith.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Lizard_Squad.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/LOST_SOULSPHERE:_Gold_Edition.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Lowtech_Remake.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/MAIS.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Megabounce.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Metroid:_Dreadnought.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/MMDCXIV_-_Journey_into_27_Century.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Monster_Scouter.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Nameless_Lite_RPG_Mod.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Nerves_of_Steel.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/njsplash.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Nobody_Told_Me_About_id.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Omega_Zero_mod.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/OMG_Weapons!__and_Monsters_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Paradise.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Parkour.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Pokémon_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Project_Ironclad.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Real_Guns_Hardcore.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Realm_of_Cheogsh.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Run_For_It!.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Slomo_Bullettime_Ultimate.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Smooth_fluids.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/SpaceDM9.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Splatterhouse_3D.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/StatsKeeper.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Sun_Damage_Omen.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/TGRDM3__Morgenstern_.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_City_of_The_Damned_:_Apocalypse.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Island.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/The_Trooper.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Thief_-_The_Trail_of_the_Arch-Heretic.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/VietDoom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Vignette_Shader.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/War_Trophies.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/WARDUST_heretic_Sprites.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Wolfenstein_3D_TC.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/X-Weapon:_Helsturm.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Xim_s_Star_Wars_Doom.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/Zion.png
convert background.png -gravity Center -size 270 -pointsize 24 -fill black -annotate +0-14 'Voted #172 mod' -pointsize 20 -fill white -annotate +0+18 'by ZDoom Community' png8:pngs/ZMovement.png
optipng -strip all pngs/*
